// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      id: 0,
      title: 'Camiseta Colón Campeón 2021 1era Equipación',
      price: '8500',
      image: '/img/campeon21rojanegra.jpg',
      description: 'Camiseta Colón Campeón 2021',
    },
    {
      id: 1,
      title: 'Camiseta Colón Campeón 2021 2da Equipación ',
      price: '8500',
      // image: 'http://localhost:3000/img/campeon21blanca.jpg',
      image: '/img/campeon21blanca.jpg',
      description: 'Camiseta Colón Campeón 2021',
    },
    {
      id: 2,
      title: 'Camiseta Colón Campeón 2021 Edición Negra/Dorada',
      price: '8500',
      image: '/img/campeon21negra.jpg',
      description: 'Camiseta Colón Campeón 2021',
    },
    {
      id: 3,
      title: 'Camiseta Colón Primera Equipación 2022 "La piel que elegimos"',
      price: '8500',
      image: '/img/1eraEquip2022LaPielQueElegimos.jpg',
      description: 'Camiseta Colón Primera Equipación 2022',
    },
    {
      id: 4,
      title: 'Camiseta Colón Segunda Equipación 2022 "Negro y Sabalero"',
      price: '8500',
      image: '/img/2daEquipacion2022NegroySabalero.jpg',
      description: 'Negro y Sabalero 2022',
    },
    {
      id: 5,
      title: 'Camiseta Colón Visitante 2022',
      price: '8500',
      image: '/img/Visitante2022Blanca.jpg',
      description: 'Camiseta Colón Blanca Visitante 2022',
    },
    {
      id: 6,
      title: 'Camiseta Colón Retro 2012',
      price: '8500',
      image: '/img/2012Colon.jpg',
      description: 'Camiseta Colón Retro 2012',
    },
    {
      id: 21,
      title: 'Camiseta Colón Retro 2011',
      price: '8500',
      image: '/img/retro2011.jpg',
      description: 'Camiseta Colón Retro 2011',
    },
    {
      id: 7,
      title: 'Camiseta Colón Alternativa 2020 Gris',
      price: '8500',
      image: '/img/Alternativa2020Gris.jpg',
      description: 'Camiseta Colón Alternativa 2020 Gris',
    },
    {
      id: 8,
      title: 'Camiseta Colón Alternativa 2020 Blanca',
      price: '8500',
      image: '/img/AlternativaBlanca2020.jpg',
      description: 'Camiseta Colón Alternativa 2020 Blanca',
    },
    {
      id: 9,
      title: 'Camiseta Colón Alternativa Retro 2013/2014',
      price: '8500',
      image: '/img/Colon20132014.jpg',
      description: 'Camiseta Colón Alternativa Retro 2013',
    },
    {
      id: 10,
      title: 'Camiseta Colón Rojinegra Retro 2011/2012',
      price: '8500',
      image: '/img/retro2011.jpg',
      description: 'Camiseta Colón Rojinegra Retro 2011/2012',
    },
    {
      id: 11,
      title: 'Camiseta Colón Visitante Retro 2011/2012',
      price: '8500',
      image: '/img/Colon201120122.png',
      description: 'Camiseta Colón Visitante Retro 2011',
    },
    {
      id: 12,
      title: 'Camiseta Colón Puma Blanca Retro 2009/2010',
      price: '8500',
      image: '/img/ColonPuma2009.png',
      description: 'Camiseta Colón Puma Blanca Retro 2009/2010',
    },
    {
      id: 13,
      title: 'Camiseta Colón Umbro Negra 2014',
      price: '8500',
      image: '/img/Umbro2014.jpg',
      description: 'Camiseta Colón Umbro Negra 2014',
    },
    {
      id: 14,
      title: 'Short Primera Equipación 2022',
      price: '4500',
      image: '/img/shortprimeraequipacion2022.jpg',
      description: 'Short Primera Equipación 2022',
    },
    {
      id: 15,
      title: 'Remera Entreno Point 2022',
      price: '4500',
      image: '/img/remeraentrenopoint.jpg',
      description: 'Remera Entreno Point 2022',
    },
    {
      id: 16,
      title: 'Remera Pre-Entreno 2022',
      price: '4500',
      image: '/img/remerapreentreno.jpg',
      description: 'Remera Pre-Entreno 2022',
    },
    {
      id: 17,
      title: 'Remera Salida Blanca',
      price: '4500',
      image: '/img/remerasalidablanca.jpg',
      description: 'Remera Salida Blanca',
    },
    {
      id: 18,
      title: 'Remera Salida Negra',
      price: '4500',
      image: '/img/remerasalidanegra.jpg',
      description: 'Remera Salida Negra',
    },
    {
      id: 19,
      title: 'Remera Salida Roja',
      price: '4500',
      image: '/img/remerasalidaroja.jpg',
      description: 'Remera Salida Roja',
    },
    {
      id: 20,
      title: 'Campera Abrigo 2022',
      price: '12000',
      image: '/img/camperaAbrigo2022.jpg',
      description: 'Campera Abrigo 2022',
    },
  ]);
}
